# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: maven
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2g

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: 777abhi/java-maven-testng-actions
      - name: Run Selenium test
        run: |
          ls
          mvn clean
          mvn -ntp -B -q clean test -Dsurefire.suiteXmlFiles=test_control/e2e_integration/newFeature.xml -Dwebdriver.chrome.url=http://selenium:4444/wd/hub
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: target-folder
          path: target
